-- Seed the species catalog from api/lib/species-catalog.js.
-- Idempotent: existing species rows are kept as-is. Without this seed the
-- species table is empty and every capture mint violates the
-- captured_cards_species_id_fkey foreign key.

INSERT INTO species
  (id, common_name, scientific_name, element, category, base_rarity, seasonality_months, nocturnal, sensitive, encyclopedia, enabled)
VALUES
  ('sky-house-sparrow', 'House Sparrow', 'Passer domesticus', 'Sky', 'Fauna', 0.05, '{}', FALSE, FALSE, 'One of the most familiar birds worldwide, thriving alongside humans in cities and villages.', TRUE),
  ('sky-rock-pigeon', 'Rock Pigeon', 'Columba livia', 'Sky', 'Fauna', 0.04, '{}', FALSE, FALSE, '', TRUE),
  ('sky-common-myna', 'Common Myna', 'Acridotheres tristis', 'Sky', 'Fauna', 0.08, '{}', FALSE, FALSE, '', TRUE),
  ('sky-red-whiskered-bulbul', 'Red-whiskered Bulbul', 'Pycnonotus jocosus', 'Sky', 'Fauna', 0.18, '{}', FALSE, FALSE, '', TRUE),
  ('sky-indian-roller', 'Indian Roller', 'Coracias benghalensis', 'Sky', 'Fauna', 0.35, '{}', FALSE, FALSE, 'Known for its brilliant blue flight feathers, revealed dramatically in flight.', TRUE),
  ('sky-kingfisher', 'Common Kingfisher', 'Alcedo atthis', 'Water', 'Fauna', 0.42, '{}', FALSE, FALSE, '', TRUE),
  ('sky-blue-billed-cuckoo', 'Blue-billed Cuckoo', 'Cuculus inflexus', 'Water', 'Fauna', 0.78, '{}', FALSE, FALSE, 'A rare cuckoo found in dense forests. Its call is a musical reminder of nature’s harmony.', TRUE),
  ('sky-barn-owl', 'Barn Owl', 'Tyto alba', 'Sky', 'Fauna', 0.55, '{}', TRUE, FALSE, '', TRUE),
  ('sky-spotted-owlet', 'Spotted Owlet', 'Athene brama', 'Sky', 'Fauna', 0.48, '{}', TRUE, FALSE, '', TRUE),
  ('sky-peacock', 'Indian Peafowl', 'Pavo cristatus', 'Sky', 'Fauna', 0.3, '{}', FALSE, FALSE, 'India’s national bird, famous for the male’s iridescent train of feathers.', TRUE),
  ('sky-flamingo', 'Greater Flamingo', 'Phoenicopterus roseus', 'Water', 'Fauna', 0.68, '{11,12,1,2,3}', FALSE, FALSE, '', TRUE),
  ('sky-bald-eagle', 'Bald Eagle', 'Haliaeetus leucocephalus', 'Sky', 'Fauna', 0.72, '{}', FALSE, FALSE, '', TRUE),
  ('sky-scarlet-macaw', 'Scarlet Macaw', 'Ara macao', 'Sky', 'Fauna', 0.82, '{}', FALSE, TRUE, '', TRUE),
  ('sky-african-grey-parrot', 'African Grey Parrot', 'Psittacus erithacus', 'Sky', 'Fauna', 0.88, '{}', FALSE, TRUE, 'Highly intelligent and social parrots native to the forests of West and Central Africa. Known for their remarkable mimicry and problem solving abilities.', TRUE),
  ('earth-red-fox', 'Red Fox', 'Vulpes vulpes', 'Earth', 'Fauna', 0.45, '{}', TRUE, FALSE, '', TRUE),
  ('earth-golden-retriever', 'Golden Retriever', 'Canis lupus familiaris', 'Earth', 'Fauna', 0.03, '{}', FALSE, FALSE, '', TRUE),
  ('earth-domestic-cat', 'Domestic Cat', 'Felis catus', 'Earth', 'Fauna', 0.02, '{}', FALSE, FALSE, '', TRUE),
  ('earth-orange-tabby-cat', 'Orange Tabby Cat', 'Felis catus', 'Earth', 'Fauna', 0.12, '{}', FALSE, FALSE, 'A beloved coat pattern caused by a sex-linked orange gene.', TRUE),
  ('earth-squirrel', 'Indian Palm Squirrel', 'Funambulus palmarum', 'Earth', 'Fauna', 0.06, '{}', FALSE, FALSE, '', TRUE),
  ('earth-mongoose', 'Indian Grey Mongoose', 'Herpestes edwardsii', 'Earth', 'Fauna', 0.32, '{}', FALSE, FALSE, '', TRUE),
  ('earth-snow-leopard', 'Snow Leopard', 'Panthera uncia', 'Earth', 'Fauna', 0.94, '{}', TRUE, TRUE, 'An elusive high-altitude big cat, one of the rarest sightings on Earth.', TRUE),
  ('earth-tiger', 'Bengal Tiger', 'Panthera tigris tigris', 'Earth', 'Fauna', 0.92, '{}', FALSE, TRUE, '', TRUE),
  ('earth-elephant', 'Asian Elephant', 'Elephas maximus', 'Earth', 'Fauna', 0.7, '{}', FALSE, TRUE, '', TRUE),
  ('earth-deer', 'Spotted Deer', 'Axis axis', 'Earth', 'Fauna', 0.28, '{}', FALSE, FALSE, '', TRUE),
  ('earth-hedgehog', 'European Hedgehog', 'Erinaceus europaeus', 'Earth', 'Fauna', 0.5, '{}', TRUE, FALSE, '', TRUE),
  ('earth-rabbit', 'European Rabbit', 'Oryctolagus cuniculus', 'Earth', 'Fauna', 0.15, '{}', FALSE, FALSE, '', TRUE),
  ('water-koi', 'Koi Carp', 'Cyprinus rubrofuscus', 'Water', 'Fauna', 0.2, '{}', FALSE, FALSE, '', TRUE),
  ('water-dolphin', 'Bottlenose Dolphin', 'Tursiops truncatus', 'Water', 'Fauna', 0.75, '{}', FALSE, TRUE, '', TRUE),
  ('water-sea-turtle', 'Green Sea Turtle', 'Chelonia mydas', 'Water', 'Fauna', 0.8, '{}', FALSE, TRUE, '', TRUE),
  ('water-frog', 'Common Frog', 'Rana temporaria', 'Water', 'Fauna', 0.18, '{}', TRUE, FALSE, '', TRUE),
  ('water-waterfall', 'Forest Waterfall', '', 'Water', 'Landscape', 0.55, '{}', FALSE, FALSE, 'A cascading freshwater feature carved into rock over centuries.', TRUE),
  ('water-river', 'River Bend', '', 'Water', 'Landscape', 0.3, '{}', FALSE, FALSE, '', TRUE),
  ('water-lake', 'Still Lake', '', 'Water', 'Landscape', 0.25, '{}', FALSE, FALSE, '', TRUE),
  ('water-tide-pool', 'Coastal Tide Pool', '', 'Water', 'Landscape', 0.4, '{}', FALSE, FALSE, '', TRUE),
  ('grass-yellow-flower', 'Yellow Wildflower', '', 'Grass', 'Flora', 0.08, '{}', FALSE, FALSE, '', TRUE),
  ('grass-rose', 'Garden Rose', 'Rosa', 'Grass', 'Flora', 0.05, '{}', FALSE, FALSE, '', TRUE),
  ('grass-sunflower', 'Sunflower', 'Helianthus annuus', 'Grass', 'Flora', 0.1, '{}', FALSE, FALSE, '', TRUE),
  ('grass-lotus', 'Sacred Lotus', 'Nelumbo nucifera', 'Grass', 'Flora', 0.22, '{}', FALSE, FALSE, '', TRUE),
  ('grass-orchid', 'Wild Orchid', 'Orchidaceae', 'Grass', 'Flora', 0.62, '{}', FALSE, TRUE, '', TRUE),
  ('grass-banyan-tree', 'Banyan Tree', 'Ficus benghalensis', 'Grass', 'Flora', 0.34, '{}', FALSE, FALSE, 'A sprawling fig tree whose aerial roots form new trunks over centuries.', TRUE),
  ('grass-oak-tree', 'English Oak', 'Quercus robur', 'Grass', 'Flora', 0.15, '{}', FALSE, FALSE, '', TRUE),
  ('grass-bamboo', 'Bamboo Grove', 'Bambusoideae', 'Grass', 'Flora', 0.12, '{}', FALSE, FALSE, '', TRUE),
  ('grass-fern', 'Fiddlehead Fern', 'Polypodiopsida', 'Grass', 'Flora', 0.2, '{}', FALSE, FALSE, '', TRUE),
  ('grass-cactus-bloom', 'Blooming Cactus', 'Cactaceae', 'Grass', 'Flora', 0.45, '{}', FALSE, FALSE, '', TRUE),
  ('grass-butterfly', 'Monarch Butterfly', 'Danaus plexippus', 'Grass', 'Fauna', 0.38, '{8,9,10}', FALSE, FALSE, '', TRUE),
  ('grass-honeybee', 'Western Honeybee', 'Apis mellifera', 'Grass', 'Fauna', 0.1, '{}', FALSE, FALSE, '', TRUE),
  ('grass-ladybird', 'Seven-spot Ladybird', 'Coccinella septempunctata', 'Grass', 'Fauna', 0.06, '{}', FALSE, FALSE, '', TRUE),
  ('fire-sunrise', 'Sunrise', '', 'Fire', 'Landscape', 0.32, '{}', FALSE, FALSE, '', TRUE),
  ('fire-sunset', 'Sunset', '', 'Fire', 'Landscape', 0.28, '{}', FALSE, FALSE, '', TRUE),
  ('fire-rainbow', 'Rainbow', '', 'Fire', 'Landscape', 0.9, '{}', FALSE, FALSE, 'A fleeting optical phenomenon formed by light refracting through rain droplets.', TRUE),
  ('fire-lightning', 'Lightning Strike', '', 'Fire', 'Landscape', 0.85, '{}', FALSE, FALSE, '', TRUE),
  ('fire-volcano', 'Volcanic Vent', '', 'Fire', 'Landscape', 0.96, '{}', FALSE, TRUE, '', TRUE),
  ('fire-campfire', 'Campfire', '', 'Fire', 'Landscape', 0.1, '{}', FALSE, FALSE, '', TRUE),
  ('fire-autumn-leaves', 'Autumn Foliage', '', 'Fire', 'Landscape', 0.22, '{9,10,11}', FALSE, FALSE, '', TRUE),
  ('earth-mountain-vista', 'Mountain Vista', '', 'Earth', 'Landscape', 0.5, '{}', FALSE, FALSE, '', TRUE),
  ('earth-canyon', 'Desert Canyon', '', 'Earth', 'Landscape', 0.6, '{}', FALSE, FALSE, '', TRUE),
  ('earth-cave', 'Limestone Cave', '', 'Earth', 'Landscape', 0.58, '{}', FALSE, FALSE, '', TRUE),
  ('sky-aurora', 'Aurora Borealis', '', 'Sky', 'Landscape', 0.97, '{}', FALSE, FALSE, 'The northern lights — charged solar particles colliding with the atmosphere.', TRUE),
  ('sky-milky-way', 'Milky Way', '', 'Sky', 'Landscape', 0.93, '{}', FALSE, FALSE, '', TRUE),
  ('grass-old-library', 'Historic Library', '', 'Grass', 'Heritage', 0.35, '{}', FALSE, FALSE, '', TRUE),
  ('earth-stone-bridge', 'Stone Bridge', '', 'Earth', 'Heritage', 0.25, '{}', FALSE, FALSE, '', TRUE),
  ('earth-ancient-ruin', 'Ancient Ruin', '', 'Earth', 'Heritage', 0.65, '{}', FALSE, TRUE, '', TRUE)
ON CONFLICT (id) DO NOTHING;
