export const GUEST_USER = {
  id: 'guest-wayfarer-777',
  displayName: 'Guest Wayfarer',
  email: 'guest@wildrealm.local',
  tier: 'Gold',
  // Blueprint §17.3 sub-level, matching the real progression engine's shape
  // so guest mode renders the same tierLabel format as a signed-in account.
  subLevel: 'III',
  tierLabel: 'Gold Explorer III',
  level: 14,
  totalXp: 7250,
  xpIntoLevel: 250,
  xpForCurrentLevel: 500,
  progressToNextLevel: 0.5,
  coins: 1450,
  streakDays: 7,
  onboardingCompletedAt: new Date().toISOString(),
};

export const GUEST_ACTIVE_QUESTS = [
  {
    id: 'g-q1',
    definitionId: 'def-1',
    title: 'Quiet Watch',
    category: 'Mind',
    description: 'Spend 10 minutes in silent observation of the wildlife around you before moving on.',
    progressValue: 1,
    targetValue: 1,
    unit: 'session',
    xpReward: 120,
    cadence: 'daily',
    status: 'completed',
  },
  {
    id: 'g-q2',
    definitionId: 'def-2',
    title: 'Trail Hydration',
    category: 'Body',
    description: 'Drink 4 full glasses of water while covering ground on the trail today.',
    progressValue: 3,
    targetValue: 4,
    unit: 'glasses',
    xpReward: 80,
    cadence: 'daily',
    status: 'active',
  },
  {
    id: 'g-q3',
    definitionId: 'def-3',
    title: 'Digital Sunset',
    category: 'Mind',
    description: 'Disconnect all screens 30 minutes before sleep to let the day’s finds settle.',
    progressValue: 0,
    targetValue: 1,
    unit: 'night',
    xpReward: 150,
    cadence: 'daily',
    status: 'active',
  },
  {
    id: 'g-q4',
    definitionId: 'def-4',
    title: 'Forest Wanderer',
    category: 'Discovery',
    description: 'Complete 3 outdoor walks in nature or green spaces this week.',
    progressValue: 2,
    targetValue: 3,
    unit: 'walks',
    xpReward: 350,
    cadence: 'weekly',
    status: 'active',
  },
];

export const GUEST_HISTORY = [
  {
    id: 'h-1',
    title: 'Starlit Vigil',
    category: 'Mind',
    xpReward: 150,
    status: 'completed',
    completedAt: new Date(Date.now() - 86400000).toISOString(),
  },
  {
    id: 'h-2',
    title: '10,000 Steps Expedition',
    category: 'Body',
    xpReward: 200,
    status: 'completed',
    completedAt: new Date(Date.now() - 172800000).toISOString(),
  },
];

export const GUEST_COLLECTIBLES = [
  {
    assetId: 'col-1',
    title: 'Aura of First Light',
    category: 'Mind',
    rarity: 'Rare',
    unlockedAt: new Date(Date.now() - 864000000).toISOString(),
    caption: 'Awarded for five straight dawn observations.',
  },
  {
    assetId: 'col-2',
    title: 'Trailblazer’s Mark',
    category: 'Body',
    rarity: 'Epic',
    unlockedAt: new Date(Date.now() - 432000000).toISOString(),
    caption: 'Earned after a 7-day trail streak.',
  },
  {
    assetId: 'col-3',
    title: 'Compass of Discovery',
    category: 'Discovery',
    rarity: 'Legendary',
    unlockedAt: new Date(Date.now() - 172800000).toISOString(),
    caption: 'Unlocked by exploring 3 distinct outdoor pathways.',
  },
];

export const GUEST_DEFINITIONS = [
  {
    id: 'def-10',
    title: 'Field Notes',
    category: 'Mind',
    description: 'Write down 3 things you noticed in the field today.',
    xpReward: 100,
    cadence: 'daily',
  },
  {
    id: 'def-11',
    title: 'Ridge Climb',
    category: 'Body',
    description: 'Cover elevation on a nearby trail or hill.',
    xpReward: 140,
    cadence: 'daily',
  },
  {
    id: 'def-12',
    title: 'Uncharted Trail',
    category: 'Discovery',
    description: 'Visit a neighborhood park or neighborhood route you have never taken.',
    xpReward: 300,
    cadence: 'weekly',
  },
];

export const GUEST_FEED = [
  {
    id: 'f-1',
    userId: 'u-101',
    displayName: 'Lyra Moonweaver',
    rankTitle: 'Gold Seeker',
    questName: 'Celestial Night Walk',
    xpEarned: 250,
    createdAt: new Date(Date.now() - 3600000).toISOString(),
  },
  {
    id: 'f-2',
    userId: 'u-102',
    displayName: 'Theron Ironheart',
    rankTitle: 'Silver Pathfinder',
    questName: '100 Pushup Trial',
    xpEarned: 180,
    createdAt: new Date(Date.now() - 14400000).toISOString(),
  },
];

export const GUEST_FRIENDS = [
  {
    userId: 'u-mira',
    displayName: 'Mira Fern',
    totalXp: 2840,
    streakDays: 12,
    rankTitle: 'Bronze Explorer IV',
    status: 'accepted',
  },
  {
    userId: 'u-arjun',
    displayName: 'Arjun Vale',
    totalXp: 760,
    streakDays: 4,
    rankTitle: 'Bronze Explorer I',
    status: 'accepted',
  },
  {
    userId: 'u-nila',
    displayName: 'Nila Skies',
    totalXp: 5320,
    streakDays: 21,
    rankTitle: 'Silver Explorer III',
    status: 'accepted',
  },
];

// Guest mode has no backend, so it serves a small slice of the same curated
// hotspots the API returns. Signed-in sessions always read the real table.
export const GUEST_WORLD_HOTSPOTS = [
  { id: 'demo-cubbon-park', name: 'Cubbon Park', category: 'Parks', description: 'A 300-acre green lung in the middle of the city, dense with old rain trees and resident birdlife.', gps: { lat: 12.9763, lng: 77.5924 }, region: 'Bengaluru, India', featuredSpecies: ['sky-house-sparrow', 'sky-common-myna'], isDemo: true },
  { id: 'demo-hebbal-lake', name: 'Hebbal Lake', category: 'Birding', description: 'Wetland margins that draw pelicans, herons and wintering waterfowl at dawn.', gps: { lat: 13.0356, lng: 77.5913 }, region: 'Bengaluru, India', featuredSpecies: ['sky-kingfisher', 'sky-flamingo'], isDemo: true },
  { id: 'demo-jog-falls', name: 'Jog Falls', category: 'Waterfalls', description: 'The Sharavathi drops in four distinct cascades — loudest and fullest just after the monsoon.', gps: { lat: 14.2295, lng: 74.8126 }, region: 'Karnataka, India', featuredSpecies: ['water-waterfall', 'water-river'], isDemo: true },
  { id: 'demo-nandi-hills', name: 'Nandi Hills', category: 'Hotspots', description: 'An escarpment that clears the morning cloud layer — the classic sunrise vantage point.', gps: { lat: 13.3702, lng: 77.6835 }, region: 'Karnataka, India', featuredSpecies: ['fire-sunrise', 'earth-mountain-vista'], isDemo: true },
];

// Guest-mode only. Signed-in sessions always read real posts from
// /api/v1/community/posts and show an empty state when there are none.
export const GUEST_COMMUNITY_POSTS = [
  {
    id: 'gp-1',
    userId: 'u-mira',
    author: { userId: 'u-mira', displayName: 'Mira Fern', totalXp: 2840, rankTitle: 'Bronze Explorer IV' },
    cardId: 'gc-1',
    discovery: { itemName: 'Rain-wet Fern', cardTitle: 'Rain-wet Fern', rarityTier: 'B', rarityGrade: 'B', rarityStars: 3, speciesId: 'grass-fern', element: 'Earth', imageRef: '/assets/verdant-explorer-banner.png', capturedAt: new Date(Date.now() - 5400000).toISOString() },
    caption: 'Tiny new fronds after the rain.',
    hashtags: ['#plants', '#walk'],
    placeLabel: 'Cubbon Park',
    gps: { lat: 12.976, lng: 77.592 },
    visibility: 'public',
    likeCount: 12,
    commentCount: 3,
    viewerLiked: false,
    createdAt: new Date(Date.now() - 5400000).toISOString(),
  },
  {
    id: 'gp-3',
    userId: 'u-nila',
    author: { userId: 'u-nila', displayName: 'Nila Skies', totalXp: 5320, rankTitle: 'Silver Explorer III' },
    cardId: 'gc-3',
    discovery: { itemName: 'Evening Cloudbreak', cardTitle: 'Evening Cloudbreak', rarityTier: 'A', rarityGrade: 'A', rarityStars: 4, speciesId: 'sky-cloudbreak', element: 'Sky', imageRef: '/auth-celestial-aperture.png', capturedAt: new Date(Date.now() - 27000000).toISOString() },
    caption: 'Sky went gold for about thirty seconds.',
    hashtags: ['#sky', '#sunset'],
    placeLabel: 'Nandi Hills',
    gps: { lat: 13.37, lng: 77.683 },
    visibility: 'public',
    likeCount: 23,
    commentCount: 4,
    viewerLiked: false,
    createdAt: new Date(Date.now() - 27000000).toISOString(),
  },
  {
    id: 'gp-4',
    userId: 'u-mira',
    author: { userId: 'u-mira', displayName: 'Mira Fern', totalXp: 2840, rankTitle: 'Bronze Explorer IV' },
    cardId: 'gc-4',
    discovery: { itemName: 'Lake Reflection', cardTitle: 'Lake Reflection', rarityTier: 'C', rarityGrade: 'C', rarityStars: 2, speciesId: 'water-lake', element: 'Water', imageRef: '/assets/verdant-explorer-banner.png', capturedAt: new Date(Date.now() - 42000000).toISOString() },
    caption: 'Quiet water, loud insects.',
    hashtags: ['#lake', '#evening'],
    placeLabel: 'Hebbal Lake',
    gps: { lat: 13.036, lng: 77.591 },
    visibility: 'public',
    likeCount: 9,
    commentCount: 0,
    viewerLiked: false,
    createdAt: new Date(Date.now() - 42000000).toISOString(),
  },
];

export const GUEST_LEADERBOARD = [
  { position: 1, userId: 'u-101', displayName: 'Lyra Moonweaver', rankTitle: 'Gold Seeker', totalXp: 12400 },
  { position: 2, userId: 'u-102', displayName: 'Theron Ironheart', rankTitle: 'Silver Pathfinder', totalXp: 9800 },
  { position: 3, userId: 'guest-wayfarer-777', displayName: 'Guest Wayfarer (You)', rankTitle: 'Gold Seeker', totalXp: 7250, isCurrentUser: true },
  { position: 4, userId: 'u-104', displayName: 'Aria Sunwalker', rankTitle: 'Novice III', totalXp: 5400 },
];

export const GUEST_CAPTURES = [
  {
    id: 'cap-1',
    itemName: 'Golden Retriever',
    category: 'Fauna',
    element: 'Earth',
    cardTitle: 'Faithful Companion',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'A beautiful golden retriever resting in the afternoon sun.',
    imageRef: '/dashboard-castle-panorama.png',
    capturedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'cap-2',
    itemName: 'Majestic Tiger',
    category: 'Fauna',
    element: 'Fire',
    cardTitle: 'King of the Jungle',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A Bengal tiger patrolling its territory.',
    imageRef: '/assets/african-grey-parrot.png',
    capturedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'cap-3',
    itemName: 'Misty Mountains',
    category: 'Landscape',
    element: 'Earth',
    cardTitle: 'Cloud Piercer',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'Jagged peaks piercing through the morning mist.',
    imageRef: '/assets/quest-compass-poster.png',
    capturedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'cap-4',
    itemName: 'Hidden Waterfall',
    category: 'Landscape',
    element: 'Water',
    cardTitle: 'Forest Cascade',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A secret waterfall deep in the ancient forest.',
    imageRef: '/assets/verdant-explorer-banner.png',
    capturedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'cap-5',
    itemName: 'Monarch Butterfly',
    category: 'Fauna',
    element: 'Sky',
    cardTitle: 'Winged Jewel',
    rarityTier: 'B',
    rarityStars: 3,
    description: 'Resting gently on a spring blossom.',
    imageRef: '/assets/blue-billed-cuckoo.png',
    capturedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'cap-6',
    itemName: 'Red Fox',
    category: 'Fauna',
    element: 'Earth',
    cardTitle: 'Forest Spirit',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A quick glimpse of red against the green undergrowth.',
    imageRef: '/dashboard-castle-panorama.png',
    capturedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'cap-7',
    itemName: 'Northern Lights',
    category: 'Landscape',
    element: 'Sky',
    cardTitle: 'Aurora Borealis',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'The sky dancing in green and purple ribbons.',
    imageRef: '/auth-celestial-aperture.png',
    capturedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'cap-8',
    itemName: 'Rainforest Canopy',
    category: 'Landscape',
    element: 'Grass',
    cardTitle: 'Emerald Roof',
    rarityTier: 'C',
    rarityStars: 2,
    description: 'Looking up through the dense tropical foliage.',
    imageRef: '/assets/blue-billed-cuckoo.png',
    capturedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'cap-9',
    itemName: 'Autumn Maple',
    category: 'Flora',
    element: 'Fire',
    cardTitle: 'Crimson Leaves',
    rarityTier: 'B',
    rarityStars: 3,
    description: 'Vibrant red leaves catching the autumn light.',
    imageRef: '/assets/quest-compass-poster.png',
    capturedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: 'cap-10',
    itemName: 'Desert Dunes',
    category: 'Landscape',
    element: 'Earth',
    cardTitle: 'Sea of Sand',
    rarityTier: 'B',
    rarityStars: 3,
    description: 'Endless rolling dunes under a harsh sun.',
    imageRef: '/dashboard-castle-panorama.png',
    capturedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'cap-11',
    itemName: 'Ocean Wave',
    category: 'Landscape',
    element: 'Water',
    cardTitle: 'Crest of Blue',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A perfectly curling wave breaking on the shore.',
    imageRef: '/assets/verdant-explorer-banner.png',
    capturedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
  },
  {
    id: 'cap-12',
    itemName: 'Wild Horses',
    category: 'Fauna',
    element: 'Earth',
    cardTitle: 'Unbridled Freedom',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'A herd of wild horses running across the plains.',
    imageRef: '/assets/quest-compass-poster.png',
    capturedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  },
  {
    id: 'cap-13',
    itemName: 'Owl in Tree',
    category: 'Fauna',
    element: 'Sky',
    cardTitle: 'Silent Watcher',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A great horned owl watching from a branch.',
    imageRef: '/assets/african-grey-parrot.png',
    capturedAt: new Date(Date.now() - 86400000 * 13).toISOString(),
  },
  {
    id: 'cap-14',
    itemName: 'Wild Mushrooms',
    category: 'Flora',
    element: 'Earth',
    cardTitle: 'Forest Floor',
    rarityTier: 'C',
    rarityStars: 2,
    description: 'Tiny fungi growing on a fallen log.',
    imageRef: '/assets/blue-billed-cuckoo.png',
    capturedAt: new Date(Date.now() - 86400000 * 14).toISOString(),
  }
];

export const GUEST_REWARDS = [
  { level: 10, amount: 200, rewardType: 'xp', label: 'Milestone XP Boost', status: 'claimed' },
  { level: 15, amount: 1, rewardType: 'badge', label: 'Badge of the Golden Sun', status: 'claimable' },
  { level: 20, amount: 1, rewardType: 'title', label: 'Title: Master Wayfarer', status: 'locked' },
];

export const GUEST_SPECIES = [
  { id: 'sky-house-sparrow', commonName: 'House Sparrow', scientificName: 'Passer domesticus', element: 'Sky', category: 'Fauna', baseRarity: 0.05, nocturnal: false, sensitive: false, seasonalityMonths: [] },
  { id: 'earth-red-fox', commonName: 'Red Fox', scientificName: 'Vulpes vulpes', element: 'Earth', category: 'Fauna', baseRarity: 0.45, nocturnal: true, sensitive: false, seasonalityMonths: [] },
  { id: 'water-waterfall', commonName: 'Forest Waterfall', scientificName: null, element: 'Water', category: 'Landscape', baseRarity: 0.55, nocturnal: false, sensitive: false, seasonalityMonths: [] },
  { id: 'grass-sunflower', commonName: 'Sunflower', scientificName: 'Helianthus annuus', element: 'Grass', category: 'Flora', baseRarity: 0.10, nocturnal: false, sensitive: false, seasonalityMonths: [] },
  { id: 'fire-sunset', commonName: 'Sunset', scientificName: null, element: 'Fire', category: 'Landscape', baseRarity: 0.28, nocturnal: false, sensitive: false, seasonalityMonths: [] },
];
