import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { QuestDetail } from './QuestDetail';
import { ProgressBar, questProgressRatio, questStatusLabel } from './QuestCard';
import { Icon, categoryIcon } from '../../components/Icon';
import { playTap } from '../../lib/useSoundEffects';
import { BottomSheet } from '../../components/motion/BottomSheet';
import { QuestSuccessModal } from '../../components/motion/QuestSuccessModal';
import { coinBalance } from '../../lib/playerEconomy';
import {
  useActiveQuests,
  useGenerateDaily,
  useGenerateWeekly,
  useGenerateMonthly,
  useMe,
} from './queries';

const CADENCE_LABEL = { daily: "Today's Quests", weekly: 'Weekly Quests', monthly: 'Monthly Quests' };

export function QuestsPage() {
  const activeQuery = useActiveQuests();
  const meQuery = useMe();
  const generateDaily = useGenerateDaily();
  const generateWeekly = useGenerateWeekly();
  const generateMonthly = useGenerateMonthly();

  const [tab, setTab] = useState('daily');
  const [selectedId, setSelectedId] = useState(null);
  const [completedQuestModal, setCompletedQuestModal] = useState(null);
  const autoGeneratedTabs = useRef(new Set());

  const quests = useMemo(() => {
    return activeQuery.data || [];
  }, [activeQuery.data]);

  const me = meQuery.data;
  const gold = coinBalance(me);
  const xpIntoLevel = Number(me?.xpIntoLevel || 0);
  const xpForCurrentLevel = Number(me?.xpForCurrentLevel || 0);
  const xpProgress = xpForCurrentLevel > 0 ? xpIntoLevel / xpForCurrentLevel : Number(me?.progressToNextLevel || 0);
  const xpRemaining = Math.max(0, xpForCurrentLevel - xpIntoLevel);

  const visibleQuests = useMemo(
    () => quests.filter((q) => !tab || (q.cadence && q.cadence.toLowerCase() === tab.toLowerCase())),
    [quests, tab],
  );

  const selected = quests.find((q) => q.id === selectedId) || null;
  const completedVisibleCount = visibleQuests.filter((quest) => quest.status === 'completed').length;

  useEffect(() => {
    const handleQuestCompleted = (event) => {
      setCompletedQuestModal(event.detail);
    };
    window.addEventListener('habbit-quest-completed', handleQuestCompleted);
    return () => window.removeEventListener('habbit-quest-completed', handleQuestCompleted);
  }, []);

  useEffect(() => {
    if (activeQuery.isLoading || activeQuery.isError || visibleQuests.length > 0) return;
    if (autoGeneratedTabs.current.has(tab)) return;
    autoGeneratedTabs.current.add(tab);
    if (tab === 'daily') generateDaily.mutate();
    else if (tab === 'weekly') generateWeekly.mutate();
    else generateMonthly.mutate();
  }, [activeQuery.isError, activeQuery.isLoading, generateDaily, generateMonthly, generateWeekly, tab, visibleQuests.length]);

  return (
    <main className="quests-shell">
      <h1 className="sr-only">Quests</h1>
      {/* Top User Bar */}
      <div className="quest-user-topbar">
        <div className="quest-explorer-main">
          <div className="quest-user-avatar" aria-hidden="true">
            <span>{(me?.displayName || 'Adventurer').split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase() || '').join('')}</span>
          </div>
          <div className="quest-explorer-copy">
            <h3>{me?.displayName || 'Adventurer'}</h3>
            {me && (
              <small>
                {me.tierLabel || `${me.tier} Explorer`} • {me.xpIntoLevel} / {me.xpForCurrentLevel} XP
              </small>
            )}
            <ProgressBar value={xpProgress} compact />
          </div>
        </div>
        <div className="quest-coin-badge" aria-label={`${gold} coins`}>
          <Icon name="coin" />
          <span>{gold.toLocaleString()}</span>
        </div>
      </div>

      {me && (
        <section className="quest-season-strip" aria-label="Explorer progression">
          <div className="quest-season-topline">
            <span>VERDANT SEASON</span>
          </div>
          <div className="quest-season-rank">
            <strong>{me.tierLabel || `${me.tier} Explorer`}</strong>
            <span>{xpIntoLevel} / {xpForCurrentLevel} XP</span>
          </div>
          <ProgressBar value={xpProgress} compact />
          {xpForCurrentLevel > 0 && (
            <p>{xpRemaining} XP to next explorer rank</p>
          )}
        </section>
      )}

      {/* Cadence Filter Tabs */}
      <div className="quest-cadence-tabs" style={{ position: 'relative' }}>
        {['daily', 'weekly', 'monthly'].map((t) => {
          const isActive = tab === t;
          return (
            <motion.button
              key={t}
              type="button"
              className={`quest-cadence-btn ${isActive ? 'active' : ''}`}
              onClick={() => { playTap(); setTab(t); }}
              whileTap={{ scale: 0.95 }}
              style={{ position: 'relative', zIndex: 1 }}
            >
              {isActive && (
                <motion.div
                  layoutId="quests-tab-indicator"
                  transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                  style={{
                    position: 'absolute',
                    inset: 0,
                    background: 'rgba(255, 255, 255, 0.1)',
                    borderRadius: '999px',
                    zIndex: -1,
                    boxShadow: '0 4px 12px rgba(0,0,0,0.2)'
                  }}
                />
              )}
              <span style={{ position: 'relative', zIndex: 2 }}>{t.toUpperCase()}</span>
            </motion.button>
          );
        })}
      </div>

      {/* Quests List */}
      <div className="quests-card-list">
        <div className="quests-section-header">
          <h2>{CADENCE_LABEL[tab] || 'Quests'}</h2>
          <span>{completedVisibleCount}/{visibleQuests.length}</span>
        </div>
        {activeQuery.isLoading ? (
          <QuestLoadingStack />
        ) : visibleQuests.length === 0 ? (
          <QuestLoadingStack />
        ) : (
          <>
            {visibleQuests.map((quest) => {
              const state = questState(quest);
              const statusLabel = questDisplayStatus(quest);
              return (
                <motion.div
                  key={quest.id}
                  className={`quest-item-card ${state} rarity-${(quest.rarity || 'Common').toLowerCase()} with-photo`}
                  whileHover={{ scale: 1.01 }}
                  onClick={() => { playTap(); setSelectedId(quest.id); }}
                >
                  <div className="quest-card-content">
                    <div className="quest-card-topline">
                      <span className="quest-rarity-mark">
                        <Icon name={categoryIcon(quest.category)} />
                        {(quest.rarity || quest.category || 'Quest').toUpperCase()}
                      </span>
                      <span className="quest-xp-reward">+{quest.xpReward} XP</span>
                    </div>
                    <div className="quest-row-main">
                      <h4 className="quest-item-title">{quest.title}</h4>
                      <p className="quest-item-instruction">{quest.description || `Capture ${quest.targetValue} ${quest.unit || 'finds'} to complete this quest.`}</p>
                      <div className="quest-row-meta">
                        <span className="quest-progress-num">{quest.progressValue}/{quest.targetValue} {quest.unit}</span>
                        <span className="quest-reward-pill">XP {quest.xpReward}</span>
                        {quest.coinReward > 0 && (
                          <span className="quest-reward-pill is-coin">
                            <Icon name="coin" /> {quest.coinReward}
                          </span>
                        )}
                      </div>
                      <ProgressBar value={questProgressRatio(quest)} compact />
                      <div className="quest-card-footer">
                        <span className="quest-status-copy">{statusLabel}</span>
                        <span className="quest-action-copy">{questActionLabel(quest)}</span>
                      </div>
                    </div>

                    <AnimatePresence mode="wait">
                      {state === 'completed' ? (
                        <motion.div
                          key="done"
                          initial={{ scale: 0, opacity: 0, rotate: -45 }}
                          animate={{ scale: 1, opacity: 1, rotate: 0 }}
                          transition={{ type: 'spring', stiffness: 400, damping: 20 }}
                          className="quest-claim-btn"
                          style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'transparent', border: '1px solid var(--quest-gold-dim)', color: 'var(--quest-gold-bright)' }}
                        >
                          ✔
                        </motion.div>
                      ) : (
                        <motion.button
                          key="claim"
                          initial={{ opacity: 1 }}
                          exit={{ scale: 0, opacity: 0 }}
                          type="button"
                          className="quest-claim-btn glass"
                          whileTap={{ scale: 0.9 }}
                          onClick={(e) => {
                            e.stopPropagation();
                            playTap();
                            setSelectedId(quest.id);
                          }}
                        >
                          {questActionLabel(quest)}
                        </motion.button>
                      )}
                    </AnimatePresence>
                  </div>
                </motion.div>
              );
            })}
          </>
        )}
      </div>

      {/* Selected Quest Modal Sheet */}
      <AnimatePresence>
        {selected && (
          <BottomSheet isOpen={!!selected} onClose={() => setSelectedId(null)}>
            <QuestDetail quest={selected} />
          </BottomSheet>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {completedQuestModal && (
          <QuestSuccessModal
            quest={completedQuestModal.quest || completedQuestModal}
            onClose={() => setCompletedQuestModal(null)}
          />
        )}
      </AnimatePresence>
    </main>
  );
}

function QuestLoadingStack() {
  return (
    <div className="quest-loading-stack" role="status" aria-live="polite">
      <div className="quest-compact-loader">
        <span />
        <div>
          <strong>Preparing today's quests</strong>
          <p>Finding something worth exploring...</p>
        </div>
      </div>
      {[0, 1, 2].map((item) => (
        <div key={item} className="quest-skeleton-card" aria-hidden="true">
          <span />
          <strong />
          <p />
        </div>
      ))}
    </div>
  );
}

function questState(quest) {
  if (quest.status === 'completed') return 'completed';
  if (quest.status === 'pending_verification') return 'pending';
  if (quest.status === 'rejected') return 'needs-work';
  if (quest.progressValue > 0) return 'in-progress';
  return 'not-started';
}

function questActionLabel(quest) {
  if (quest.status === 'completed') return 'DONE';
  if (quest.status === 'pending_verification') return 'REVIEW';
  if (quest.status === 'rejected') return 'RETRY';
  return quest.progressValue > 0 ? 'OPEN' : 'START';
}

function questDisplayStatus(quest) {
  if (quest.status === 'active' && Number(quest.progressValue || 0) === 0) return 'Not started';
  return questStatusLabel(quest);
}
