import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { QuestDetail } from './QuestDetail';
import { ProgressBar, questProgressRatio } from './QuestCard';
import { Icon, categoryIcon } from '../../components/Icon';
import { playTap } from '../../lib/useSoundEffects';
import { BottomSheet } from '../../components/motion/BottomSheet';
import { QuestSuccessModal } from '../../components/motion/QuestSuccessModal';
import { coinBalance } from '../../lib/playerEconomy';
import {
  useActiveQuests,
  useGenerateDaily,
  useGenerateWeekly,
  useGenerateMonthly,
  useMe,
} from './queries';

const CADENCE_LABEL = { daily: "Today's Quests", weekly: 'Weekly Quests', monthly: 'Monthly Quests' };

export function QuestsPage() {
  const activeQuery = useActiveQuests();
  const meQuery = useMe();
  const generateDaily = useGenerateDaily();
  const generateWeekly = useGenerateWeekly();
  const generateMonthly = useGenerateMonthly();

  const [tab, setTab] = useState('daily');
  const [selectedId, setSelectedId] = useState(null);
  const [completedQuestModal, setCompletedQuestModal] = useState(null);
  const autoGeneratedTabs = useRef(new Set());

  const quests = useMemo(() => {
    return activeQuery.data || [];
  }, [activeQuery.data]);

  const me = meQuery.data;
  const gold = coinBalance(me);
  const xpIntoLevel = Number(me?.xpIntoLevel || 0);
  const xpForCurrentLevel = Number(me?.xpForCurrentLevel || 0);
  const xpProgress = xpForCurrentLevel > 0 ? xpIntoLevel / xpForCurrentLevel : Number(me?.progressToNextLevel || 0);
  const xpRemaining = Math.max(0, xpForCurrentLevel - xpIntoLevel);

  const visibleQuests = useMemo(
    () => quests.filter((q) => !tab || (q.cadence && q.cadence.toLowerCase() === tab.toLowerCase())),
    [quests, tab],
  );
  const currentGenerate = tab === 'daily' ? generateDaily : tab === 'weekly' ? generateWeekly : generateMonthly;

  const selected = quests.find((q) => q.id === selectedId) || null;
  const completedVisibleCount = visibleQuests.filter((quest) => quest.status === 'completed').length;

  useEffect(() => {
    const handleQuestCompleted = (event) => {
      setCompletedQuestModal(event.detail);
    };
    window.addEventListener('habbit-quest-completed', handleQuestCompleted);
    return () => window.removeEventListener('habbit-quest-completed', handleQuestCompleted);
  }, []);

  useEffect(() => {
    if (activeQuery.isLoading || activeQuery.isError || visibleQuests.length > 0) return;
    if (autoGeneratedTabs.current.has(tab)) return;
    autoGeneratedTabs.current.add(tab);
    if (tab === 'daily') generateDaily.mutate();
    else if (tab === 'weekly') generateWeekly.mutate();
    else generateMonthly.mutate();
  }, [activeQuery.isError, activeQuery.isLoading, generateDaily, generateMonthly, generateWeekly, tab, visibleQuests.length]);

  return (
    <main className="quests-shell">
      <h1 className="sr-only">Quests</h1>
      {/* Explorer Profile */}
      <section className="quest-explorer-card" aria-label="Explorer progression">
        <div className="quest-user-topbar">
          <div className="quest-user-avatar" aria-hidden="true">
            <span>{(me?.displayName || 'Adventurer').split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase() || '').join('')}</span>
          </div>
          <div className="quest-user-identity">
            <h3>{me?.displayName || 'Adventurer'}</h3>
            <small>{me?.tierLabel || `${me?.tier || 'Bronze'} Explorer`} · Level {me?.level || 1}</small>
            <ProgressBar value={xpProgress} compact />
          </div>
          <div className="quest-user-economy">
            <span>{gold.toLocaleString()}</span>
            <small>coins</small>
          </div>
        </div>
        <div className="quest-season-strip">
          <div>
            <span style={{ color: 'var(--wr-walnut)', fontWeight: 800 }}>Rank Progress</span>
            <strong style={{ color: 'var(--wr-forest)', fontWeight: 900 }}>{me?.tierLabel || `${me?.tier || 'Bronze'} Explorer`}</strong>
          </div>
          <div style={{ textAlign: 'right' }}>
            <span style={{ color: 'var(--wr-walnut)', fontWeight: 800 }}>{xpIntoLevel} / {xpForCurrentLevel || 250} XP</span>
            {xpRemaining > 0 && <small style={{ display: 'block', color: 'var(--wr-walnut-muted)', fontWeight: 700 }}>{xpRemaining} XP to next rank</small>}
          </div>
        </div>
      </section>

      {/* Cadence Filter Tabs */}
      <div className="quest-cadence-tabs">
        {['daily', 'weekly', 'monthly'].map((t) => {
          const isActive = tab === t;
          return (
            <motion.button
              key={t}
              type="button"
              className={`quest-cadence-btn ${isActive ? 'active' : ''}`}
              onClick={() => { playTap(); setTab(t); }}
              whileTap={{ scale: 0.95 }}
            >
              {t.toUpperCase()}
            </motion.button>
          );
        })}
      </div>

      {/* Quests List */}
      <div className="quests-card-list">
        <div className="quests-section-header">
          <h2>{CADENCE_LABEL[tab]}</h2>
          <span>{completedVisibleCount}/{visibleQuests.length}</span>
        </div>
        {activeQuery.isLoading || currentGenerate.isPending ? (
          <QuestLoadingStack />
        ) : activeQuery.isError ? (
          <QuestListState
            title="Quests could not load"
            message="Check your connection and try again."
            actionLabel="Retry"
            onAction={() => activeQuery.refetch()}
          />
        ) : visibleQuests.length === 0 ? (
          <QuestListState
            title={`No ${tab} quests yet`}
            message="Generate a fresh set when you are ready to explore."
            actionLabel={`Generate ${tab}`}
            onAction={() => currentGenerate.mutate()}
          />
        ) : (
          <>
            {visibleQuests.map((quest) => {
              const state = questState(quest);
              return (
                <motion.div
                  key={quest.id}
                  className={`quest-item-card ${state} rarity-${(quest.rarity || 'Common').toLowerCase()}`}
                  whileHover={{ scale: 1.01 }}
                  onClick={() => { playTap(); setSelectedId(quest.id); }}
                >
                  <div className="quest-card-content">
                    <div className="quest-card-topline">
                      <span className="quest-rarity-mark">
                        <Icon name={categoryIcon(quest.category)} />
                        {quest.rarity || 'Common'}
                      </span>
                      <span className="quest-xp-reward">+{quest.xpReward} XP</span>
                    </div>
                    <div className={`quest-row-thumb category-${(quest.category || 'Discovery').toLowerCase()}`}>
                      <img src={questThumbSrc(quest)} alt="" loading="lazy" decoding="async" />
                    </div>
                    <div className="quest-row-main">
                      <h4 className="quest-item-title">{quest.title}</h4>
                      <p className="quest-item-instruction">
                        {quest.description || `Capture ${quest.targetValue} ${quest.unit || 'finds'} to complete this quest.`}
                      </p>
                      <div className="quest-row-meta">
                        <ProgressBar value={questProgressRatio(quest)} compact />
                        <span className="quest-progress-num">
                          {quest.progressValue || 0}/{quest.targetValue || 1}
                        </span>
                      </div>
                    </div>
                    <button type="button" className="quest-card-action" aria-label="View" title={`View ${quest.title}`}>
                      {questActionLabel(quest)}
                    </button>
                  </div>
                </motion.div>
              );
            })}
          </>
        )}
      </div>

      {/* Selected Quest Modal Sheet */}
      <AnimatePresence>
        {selected && (
          <BottomSheet isOpen={!!selected} onClose={() => setSelectedId(null)}>
            <QuestDetail quest={selected} />
          </BottomSheet>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {completedQuestModal && (
          <QuestSuccessModal
            quest={completedQuestModal.quest || completedQuestModal}
            onClose={() => setCompletedQuestModal(null)}
          />
        )}
      </AnimatePresence>
    </main>
  );
}

function QuestListState({ title, message, actionLabel, onAction }) {
  return (
    <div className="quest-loop-empty" role="status">
      <Icon name="scroll" />
      <h2>{title}</h2>
      <p>{message}</p>
      <button type="button" className="quest-card-action" onClick={onAction}>
        {actionLabel}
      </button>
    </div>
  );
}

function QuestLoadingStack() {
  return (
    <div className="quest-loading-stack" role="status" aria-live="polite">
      <div className="quest-compact-loader">
        <span />
        <div>
          <strong>Preparing today's quests</strong>
          <p>Finding something worth exploring...</p>
        </div>
      </div>
      {[0, 1, 2].map((item) => (
        <div key={item} className="quest-skeleton-card" aria-hidden="true">
          <span />
          <strong />
          <p />
        </div>
      ))}
    </div>
  );
}

function questState(quest) {
  if (quest.status === 'completed') return 'completed';
  if (quest.status === 'pending_verification') return 'pending';
  if (quest.status === 'rejected') return 'needs-work';
  if (quest.progressValue > 0) return 'in-progress';
  return 'not-started';
}

function questThumbSrc(quest) {
  const text = `${quest.category || ''} ${quest.title || ''} ${quest.description || ''}`.toLowerCase();
  if (/bird|watch|observe|wildlife|fauna|quiet/.test(text)) return '/assets/blue-billed-cuckoo.png';
  if (/water|drink|hydration|waterfall|lake|river/.test(text)) return '/assets/verdant-explorer-banner.png';
  if (/season|reward|rank|gold/.test(text)) return '/assets/mystery-chest.png';
  if (/mind|journal|reflect|note/.test(text)) return '/quest-scholar-hero.png';
  return '/assets/verdant-explorer-banner.png';
}

function questActionLabel(quest) {
  if (quest.status === 'completed') return 'DONE';
  if (quest.status === 'pending_verification') return 'REVIEW';
  if (quest.status === 'rejected') return 'RETRY';
  return quest.progressValue > 0 ? 'OPEN' : 'START';
}
