import { useEffect, useMemo, useRef, useState } from 'react';
import { AnimatePresence, motion } from 'framer-motion';
import { QuestDetail } from './QuestDetail';
import { ProgressBar, questProgressRatio } from './QuestCard';
import { Icon, categoryIcon } from '../../components/Icon';
import { playTap } from '../../lib/useSoundEffects';
import { BottomSheet } from '../../components/motion/BottomSheet';
import { QuestSuccessModal } from '../../components/motion/QuestSuccessModal';
import { coinBalance } from '../../lib/playerEconomy';
import {
  useActiveQuests,
  useGenerateDaily,
  useGenerateWeekly,
  useGenerateMonthly,
  useMe,
} from './queries';

export function QuestsPage() {
  const activeQuery = useActiveQuests();
  const meQuery = useMe();
  const generateDaily = useGenerateDaily();
  const generateWeekly = useGenerateWeekly();
  const generateMonthly = useGenerateMonthly();

  const [tab, setTab] = useState('daily');
  const [selectedId, setSelectedId] = useState(null);
  const [completedQuestModal, setCompletedQuestModal] = useState(null);
  const autoGeneratedTabs = useRef(new Set());

  const quests = useMemo(() => {
    return activeQuery.data || [];
  }, [activeQuery.data]);

  const me = meQuery.data;
  const gold = coinBalance(me);

  const visibleQuests = useMemo(
    () => quests.filter((q) => !tab || (q.cadence && q.cadence.toLowerCase() === tab.toLowerCase())),
    [quests, tab],
  );

  const selected = quests.find((q) => q.id === selectedId) || null;

  useEffect(() => {
    const handleQuestCompleted = (event) => {
      setCompletedQuestModal(event.detail);
    };
    window.addEventListener('habbit-quest-completed', handleQuestCompleted);
    return () => window.removeEventListener('habbit-quest-completed', handleQuestCompleted);
  }, []);

  useEffect(() => {
    if (activeQuery.isLoading || activeQuery.isError || visibleQuests.length > 0) return;
    if (autoGeneratedTabs.current.has(tab)) return;
    autoGeneratedTabs.current.add(tab);
    if (tab === 'daily') generateDaily.mutate();
    else if (tab === 'weekly') generateWeekly.mutate();
    else generateMonthly.mutate();
  }, [activeQuery.isError, activeQuery.isLoading, generateDaily, generateMonthly, generateWeekly, tab, visibleQuests.length]);

  return (
    <main className="quests-shell">
      <h1 className="sr-only">Quests</h1>
      {/* Top User Bar */}
      <div className="quest-user-topbar">
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <div className="quest-user-avatar" aria-hidden="true">
            <span>{(me?.displayName || 'Adventurer').split(/\s+/).slice(0, 2).map((part) => part[0]?.toUpperCase() || '').join('')}</span>
          </div>
          <div>
            <h3 style={{ fontSize: '0.95rem', margin: 0, fontWeight: '800' }}>{me?.displayName || 'Adventurer'}</h3>
            {me && (
              <small style={{ color: 'var(--wild-emerald)', fontSize: '0.72rem', fontWeight: '700' }}>
                {me.tierLabel || `${me.tier} Explorer`} • {me.xpIntoLevel} / {me.xpForCurrentLevel} XP
              </small>
            )}
          </div>
        </div>
        <div className="quest-coin-badge" aria-label={`${gold} coins`}>
          <Icon name="coin" />
          <span>{gold.toLocaleString()}</span>
        </div>
      </div>

      {/* Cadence Filter Tabs */}
      <div className="quest-cadence-tabs" style={{ position: 'relative' }}>
        {['daily', 'weekly', 'monthly'].map((t) => {
          const isActive = tab === t;
          return (
            <motion.button
              key={t}
              type="button"
              className={`quest-cadence-btn ${isActive ? 'active' : ''}`}
              onClick={() => { playTap(); setTab(t); }}
              whileTap={{ scale: 0.95 }}
              style={{ position: 'relative', zIndex: 1 }}
            >
              {isActive && (
                <motion.div
                  layoutId="quests-tab-indicator"
                  transition={{ type: 'spring', stiffness: 400, damping: 30 }}
                  style={{
                    position: 'absolute',
                    inset: 0,
                    background: 'rgba(255, 255, 255, 0.1)',
                    borderRadius: '999px',
                    zIndex: -1,
                    boxShadow: '0 4px 12px rgba(0,0,0,0.2)'
                  }}
                />
              )}
              <span style={{ position: 'relative', zIndex: 2 }}>{t.toUpperCase()}</span>
            </motion.button>
          );
        })}
      </div>

      {/* Quests List */}
      <div className="quests-card-list">
        {activeQuery.isLoading ? (
          <div style={{ textAlign: 'center', padding: '40px 0', color: 'var(--wild-text-dim)' }}>Loading quests...</div>
        ) : visibleQuests.length === 0 ? (
          <div className="quests-empty-state quest-loop-empty">
            <div className="quest-loop-kicker">Next best action</div>
            <h2>Building your {tab} quest deck.</h2>
            <p>AI is choosing camera-only tasks for your streak. No upload shortcuts, no setup step.</p>
            <div className="retention-loop-rail" aria-label="Quest loop">
              <span><strong>1</strong> AI picks</span>
              <span><strong>2</strong> Capture</span>
              <span><strong>3</strong> Claim XP</span>
            </div>
            <div className="quest-auto-loader" role="status" aria-live="polite">
              <span />
              Preparing quests
            </div>
          </div>
        ) : (
          visibleQuests.map((quest) => {
            const isDone = quest.status === 'completed';
            return (
              <motion.div
                key={quest.id}
                className={`quest-item-card ${isDone ? 'completed' : ''} with-photo`}
                whileHover={{ scale: 1.01 }}
                onClick={() => { playTap(); setSelectedId(quest.id); }}
              >
                <div className="quest-card-content">
                  {/* A category crest, not a stock landscape: the previous rows
                      pulled unrelated Unsplash photos keyed off id length. */}
                  <div className={`quest-row-thumb category-${(quest.category || 'Discovery').toLowerCase()}`} aria-hidden="true">
                    <Icon name={categoryIcon(quest.category)} />
                  </div>
                  <div className="quest-row-main">
                    <h4 className="quest-item-title">{quest.title}</h4>
                    <div className="quest-row-meta">
                      <span className="quest-progress-num">{quest.progressValue}/{quest.targetValue} {quest.unit}</span>
                      <span className="quest-reward-pill">XP {quest.xpReward}</span>
                      {quest.coinReward > 0 && (
                        <span className="quest-reward-pill is-coin">
                          <Icon name="coin" /> {quest.coinReward}
                        </span>
                      )}
                    </div>
                    <ProgressBar value={questProgressRatio(quest)} compact />
                  </div>

                  <AnimatePresence mode="wait">
                    {isDone ? (
                      <motion.div
                        key="done"
                        initial={{ scale: 0, opacity: 0, rotate: -45 }}
                        animate={{ scale: 1, opacity: 1, rotate: 0 }}
                        transition={{ type: 'spring', stiffness: 400, damping: 20 }}
                        className="quest-claim-btn"
                        style={{ display: 'flex', alignItems: 'center', justifyContent: 'center', background: 'transparent', border: '1px solid var(--quest-gold-dim)', color: 'var(--quest-gold-bright)' }}
                      >
                        ✔
                      </motion.div>
                    ) : (
                      <motion.button
                        key="claim"
                        initial={{ opacity: 1 }}
                        exit={{ scale: 0, opacity: 0 }}
                        type="button"
                        className="quest-claim-btn glass"
                        whileTap={{ scale: 0.9 }}
                        onClick={(e) => {
                          e.stopPropagation();
                          playTap();
                          setSelectedId(quest.id);
                        }}
                      >
                        View
                      </motion.button>
                    )}
                  </AnimatePresence>
                </div>
              </motion.div>
            );
          })
        )}
      </div>

      {/* Selected Quest Modal Sheet */}
      <AnimatePresence>
        {selected && (
          <BottomSheet isOpen={!!selected} onClose={() => setSelectedId(null)}>
            <QuestDetail quest={selected} />
          </BottomSheet>
        )}
      </AnimatePresence>

      <AnimatePresence>
        {completedQuestModal && (
          <QuestSuccessModal
            quest={completedQuestModal.quest || completedQuestModal}
            onClose={() => setCompletedQuestModal(null)}
          />
        )}
      </AnimatePresence>
    </main>
  );
}
