const fs = require('fs');
const path = require('path');

const guestDataPath = path.join(__dirname, '../src/lib/guestData.js');
let code = fs.readFileSync(guestDataPath, 'utf8');

const newCaptures = `export const GUEST_CAPTURES = [
  {
    id: 'cap-1',
    itemName: 'Golden Retriever',
    category: 'Fauna',
    element: 'Earth',
    cardTitle: 'Faithful Companion',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'A beautiful golden retriever resting in the afternoon sun.',
    imageRef: 'https://images.unsplash.com/photo-1552053831-71594a27632d?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 1).toISOString(),
  },
  {
    id: 'cap-2',
    itemName: 'Majestic Tiger',
    category: 'Fauna',
    element: 'Fire',
    cardTitle: 'King of the Jungle',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A Bengal tiger patrolling its territory.',
    imageRef: 'https://images.unsplash.com/photo-1549366021-9f761d450615?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 2).toISOString(),
  },
  {
    id: 'cap-3',
    itemName: 'Misty Mountains',
    category: 'Landscape',
    element: 'Earth',
    cardTitle: 'Cloud Piercer',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'Jagged peaks piercing through the morning mist.',
    imageRef: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 3).toISOString(),
  },
  {
    id: 'cap-4',
    itemName: 'Hidden Waterfall',
    category: 'Landscape',
    element: 'Water',
    cardTitle: 'Forest Cascade',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A secret waterfall deep in the ancient forest.',
    imageRef: 'https://images.unsplash.com/photo-1432405972618-fc027f58c749?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 4).toISOString(),
  },
  {
    id: 'cap-5',
    itemName: 'Monarch Butterfly',
    category: 'Fauna',
    element: 'Sky',
    cardTitle: 'Winged Jewel',
    rarityTier: 'B',
    rarityStars: 3,
    description: 'Resting gently on a spring blossom.',
    imageRef: 'https://images.unsplash.com/photo-1534265111162-cebbf5287f32?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 5).toISOString(),
  },
  {
    id: 'cap-6',
    itemName: 'Red Fox',
    category: 'Fauna',
    element: 'Earth',
    cardTitle: 'Forest Spirit',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A quick glimpse of red against the green undergrowth.',
    imageRef: 'https://images.unsplash.com/photo-1474511320723-9a56873867b5?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 6).toISOString(),
  },
  {
    id: 'cap-7',
    itemName: 'Northern Lights',
    category: 'Landscape',
    element: 'Sky',
    cardTitle: 'Aurora Borealis',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'The sky dancing in green and purple ribbons.',
    imageRef: 'https://images.unsplash.com/photo-1531366936337-7793249eb374?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 7).toISOString(),
  },
  {
    id: 'cap-8',
    itemName: 'Rainforest Canopy',
    category: 'Landscape',
    element: 'Grass',
    cardTitle: 'Emerald Roof',
    rarityTier: 'C',
    rarityStars: 2,
    description: 'Looking up through the dense tropical foliage.',
    imageRef: 'https://images.unsplash.com/photo-1516026672322-bc52d61a55d5?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 8).toISOString(),
  },
  {
    id: 'cap-9',
    itemName: 'Autumn Maple',
    category: 'Flora',
    element: 'Fire',
    cardTitle: 'Crimson Leaves',
    rarityTier: 'B',
    rarityStars: 3,
    description: 'Vibrant red leaves catching the autumn light.',
    imageRef: 'https://images.unsplash.com/photo-1507371341162-763b5e419408?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 9).toISOString(),
  },
  {
    id: 'cap-10',
    itemName: 'Desert Dunes',
    category: 'Landscape',
    element: 'Earth',
    cardTitle: 'Sea of Sand',
    rarityTier: 'B',
    rarityStars: 3,
    description: 'Endless rolling dunes under a harsh sun.',
    imageRef: 'https://images.unsplash.com/photo-1509316785289-025f5b846b35?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 10).toISOString(),
  },
  {
    id: 'cap-11',
    itemName: 'Ocean Wave',
    category: 'Landscape',
    element: 'Water',
    cardTitle: 'Crest of Blue',
    rarityTier: 'A',
    rarityStars: 4,
    description: 'A perfectly curling wave breaking on the shore.',
    imageRef: 'https://images.unsplash.com/photo-1505118380757-91f5f5632de0?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 11).toISOString(),
  },
  {
    id: 'cap-12',
    itemName: 'Wild Horses',
    category: 'Fauna',
    element: 'Earth',
    cardTitle: 'Unbridled Freedom',
    rarityTier: 'S',
    rarityStars: 5,
    description: 'A herd of wild horses running across the plains.',
    imageRef: 'https://images.unsplash.com/photo-1534067783941-51c9c23ecefd?auto=format&fit=crop&w=800&q=80',
    capturedAt: new Date(Date.now() - 86400000 * 12).toISOString(),
  }
];`;

code = code.replace(/export const GUEST_CAPTURES = \[[\s\S]*?\];/, newCaptures);
fs.writeFileSync(guestDataPath, code);
